# Generated by Django 5.1.1 on 2024-10-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_training_programs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
